/*

class MatchesModel
{
  fixture? Fixture;
  Team? home;
  Team? away;
  Goal? goal;
  MatchesModel({
    this.Fixture,
    this.home,
    this.away,
    this.goal
  });
  MatchesModel.fromJson(Map<String,dynamic>? json)
  {
    Fixture = fixture.fromjson(json?['fixture']);
    home = Team.fromjson(json?['teams']['home']) ;
    away = Team.fromjson(json?['teams']['away']) ;
    goal = Goal.fromjson(json?['goals']);

  }
}

class fixture{
  int? id;
  int? date;
  status? stat;
  fixture({
    this.id,
    this.date,
    this.stat
  });
  fixture.fromjson(Map<String,dynamic> json)
  {
    id = json['id'];
    date = json['date'];
    stat = status.fromjson(json['status']) ;
  }
}

class status{
  int? time;
  String? long;
  status({this.time , this.long});
  status.fromjson(Map<String,dynamic>? json)
  {
    time = json!['elapsed'];
    long = json['long'];
  }
}

class Team{
  int? id;
  String? name;
  String? logo;
  bool? winner;

  Team({
    this.id,
    this.name,
    this.logo,
    this.winner,
});

  Team.fromjson(Map<String,dynamic>? json)
  {
    id = json!['id'];
    name = json['name'];
    logo = json['logo'];
    winner = json['winner'];
  }
}

class Goal{
  int? home;
  int? away;
  Goal({
    this.home,
    this.away
});
  Goal.fromjson(Map<String,dynamic>? json)
  {
    home = json!['home'];
    away = json['away'];
  }
}
*/
class Autogenerated {
  Fixture? fixture;
  League? league;
  Teams? teams;
  Goals? goals;
  Score? score;

  Autogenerated(
      {this.fixture, this.league, this.teams, this.goals, this.score});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    fixture =
    json['fixture'] != null ? new Fixture.fromJson(json['fixture']) : null;
    league =
    json['league'] != null ? new League.fromJson(json['league']) : null;
    teams = json['teams'] != null ? new Teams.fromJson(json['teams']) : null;
    goals = json['goals'] != null ? new Goals.fromJson(json['goals']) : null;
    score = json['score'] != null ? new Score.fromJson(json['score']) : null;
  }

}

class Fixture {
  int? id;
  String? referee;
  String? timezone;
  String? date;
  int? timestamp;
  Periods? periods;
  Venue? venue;
  Status? status;

  Fixture(
      {this.id,
        this.referee,
        this.timezone,
        this.date,
        this.timestamp,
        this.periods,
        this.venue,
        this.status});

  Fixture.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    referee = json['referee'];
    timezone = json['timezone'];
    date = json['date'];
    timestamp = json['timestamp'];
    periods =
    json['periods'] != null ? new Periods.fromJson(json['periods']) : null;
    venue = json['venue'] != null ? new Venue.fromJson(json['venue']) : null;
    status =
    json['status'] != null ? new Status.fromJson(json['status']) : null;
  }

}

class Periods {
  int? first;
  int? second;

  Periods({this.first, this.second});

  Periods.fromJson(Map<String, dynamic> json) {
    first = json['first'];
    second = json['second'];
  }


}

class Venue {
  int? id;
  String? name;
  String? city;

  Venue({this.id, this.name, this.city});

  Venue.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    city = json['city'];
  }


}

class Status {
  String? long;
  String? short;
  int? elapsed;

  Status({this.long, this.short, this.elapsed});

  Status.fromJson(Map<String, dynamic> json) {
    long = json['long'];
    short = json['short'];
    elapsed = json['elapsed'];
  }

}

class League {
  int? id;
  String? name;
  String? country;
  String? logo;
  String? flag;
  int? season;
  String? round;

  League(
      {this.id,
        this.name,
        this.country,
        this.logo,
        this.flag,
        this.season,
        this.round});

  League.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    country = json['country'];
    logo = json['logo'];
    flag = json['flag'];
    season = json['season'];
    round = json['round'];
  }

}

class Teams {
  Home? home;
  Home? away;

  Teams({this.home, this.away});

  Teams.fromJson(Map<String, dynamic> json) {
    home = json['home'] != null ? new Home.fromJson(json['home']) : null;
    away = json['away'] != null ? new Home.fromJson(json['away']) : null;
  }

}

class Home {
  int? id;
  String? name;
  String? logo;
  bool? winner;

  Home({this.id, this.name, this.logo, this.winner});

  Home.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    logo = json['logo'];
    winner = json['winner'];
  }

}

class Goals {
  int? home;
  int? away;

  Goals({this.home, this.away});

  Goals.fromJson(Map<String, dynamic> json) {
    home = json['home'];
    away = json['away'];
  }

}

class Score {
  Goals? halftime;
  Goals? fulltime;
  Extratime? extratime;
  Extratime? penalty;

  Score({this.halftime, this.fulltime, this.extratime, this.penalty});

  Score.fromJson(Map<String, dynamic> json) {
    halftime =
    json['halftime'] != null ? new Goals.fromJson(json['halftime']) : null;
    fulltime =
    json['fulltime'] != null ? new Goals.fromJson(json['fulltime']) : null;
    extratime = json['extratime'] != null
        ? new Extratime.fromJson(json['extratime'])
        : null;
    penalty = json['penalty'] != null
        ? new Extratime.fromJson(json['penalty'])
        : null;
  }

}

class Extratime {
  Null? home;
  Null? away;

  Extratime({this.home, this.away});

  Extratime.fromJson(Map<String, dynamic> json) {
    home = json['home'];
    away = json['away'];
  }

}